name: ci

on: [push, pull_request]

jobs:
  check:
    name: Static code check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: cppcheck
        run:
          sudo apt-get update && sudo apt-get -y install cppcheck && make check

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install bison & flex
        run: sudo apt-get update && sudo apt-get -y install flex bison
      - name: checkout submodule GoogleTest
        run: make checkout
      - name: run tests
        run: make test
